development:
  adapter: postgresql
  encoding: unicode
  database: chitter
  pool: 2
  username: test
  password: 1234

test:
  adapter: postgresql
  encoding: unicode
  database: chitter_test
  pool: 2
  username: test
  password: 1234